public class Campaign
{
    public DateTime CREATED_AT { get; set; }
    public string? Category { get; set; }
    public string? Sub_Category { get; set; }
    public string? Topic { get; set; }
    public string? Score { get; set; }
    public string? Sha256_Lc_Hem { get; set; }
    public string? Up_Id { get; set; }
    public string? First_Name { get; set; }
    public string? Last_Name { get; set; }
    public string? Business_Email { get; set; }
    public string? Programmatic_Business_Emails { get; set; }
    public string? Mobile_Phone { get; set; }
    public string? Direct_Number { get; set; }
    public string? Personal_Phone { get; set; }
    public string? Linkedin_Url { get; set; }
    public string? Personal_Address { get; set; }
    public string? Personal_Address_2 { get; set; }
    public string? Personal_City { get; set; }
    public string? Personal_State { get; set; }
    public string? Personal_Zip { get; set; }
    public string? Personal_Zip4 { get; set; }
    public string? Personal_Emails { get; set; }
    public string? Additional_Personal_Emails { get; set; }
    public string? Gender { get; set; }
    public string? Age_Range { get; set; }
    public string? Married { get; set; }
    public string? Children { get; set; }
    public string? Income_Range { get; set; }
    public string? Net_Worth { get; set; }
    public string? Homeowner { get; set; }
    public string? Job_Title { get; set; }
    public string? Seniority_Level { get; set; }
    public string? Department { get; set; }
    public string? Professional_Address { get; set; }
    public string? Professional_Address_2 { get; set; }
    public string? Professional_City { get; set; }
    public string? Professional_State { get; set; }
    public string? Professional_Zip { get; set; }
    public string? Professional_Zip4 { get; set; }
    public string? Company_Name { get; set; }
    public string? Company_Domain { get; set; }
    public string? Company_Phone { get; set; }
    public string? Company_Sic { get; set; }
    public string? Company_Address { get; set; }
    public string? Company_City { get; set; }
    public string? Company_State { get; set; }
    public string? Company_Zip { get; set; }
    public string? Company_Linkedin_Url { get; set; }
    public string? Company_Revenue { get; set; }
    public string? Company_Employee_Count { get; set; }
    public string? Primary_Industry { get; set; }
    public string? Business_Email_Validation_Status { get; set; }
    public string? Business_Email_Last_Seen { get; set; }
    public string? Personal_Emails_Validation_Status { get; set; }
    public string? Personal_Emails_Last_Seen { get; set; }
    public string? Company_Last_Updated { get; set; }
    public string? Job_Title_Last_Updated { get; set; }
    public string? Last_Updated { get; set; }
    public string? Work_History { get; set; }
    public string? Education_History { get; set; }
    public string? Company_Description { get; set; }
    public string? Related_Domains { get; set; }
    public string? Social_Connections { get; set; }
    public string? Dpv_Code { get; set; }
    public string? Company_Naics { get; set; }
}
